spring.application.name=family-health-guardian

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/family_health_guardian
spring.datasource.username=root
spring.datasource.password=Prabhuteja@2008
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=false

# Server
server.port=8080

# Increase File Upload Limits (Max File Size & Request Size)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.mvc.format.date=yyyy-MM-dd